kind: Service
apiVersion: v1
metadata:
  name: trinitycore-worldserver
  namespace: trinitycore-master
  labels:
    app.kubernetes.io/part-of: trinitycore
spec:
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 31085
      nodePort: 31085
  type: NodePort
  selector:
    app: trinitycore-worldserver
