kind: Service
apiVersion: v1
metadata:
  name: trinitycore-authserver
  namespace: trinity
  labels:
    app.kubernetes.io/part-of: trinitycore
spec:
  ports:
    - protocol: TCP
      port: 3724
      targetPort: 3724
      nodePort: 32024
  type: NodePort
  selector:
    app: trinitycore-authserver
